{
  config,
  lib,
  pkgs,
  nixvirt,
  looking-glass,
  ...
}:

with lib;
with types;

let
  cfg = config.nix-vm;

  nixvirtLib = nixvirt.lib;

  vmSubmodule = types.submoduleWith {
    specialArgs = {
      inherit nixvirtLib pkgs;
      hostConfig = config;
    };
    modules = [
      ../modules/core.nix
    ];
  };
in
{
  imports = [
    ./looking-glass.nix
  ];

  options.nix-vm = {
    vms = mkOption {
      type = attrsOf vmSubmodule;
      default = { };
      description = "VMs definition";
    };

    hostResources = mkOption {
      type = attrs;
      default = { };
      description = "Global resources computed by host modules to be shared with VMs.";
    };

    facter = {
      reportPath = mkOption {
        type = nullOr path;
        default = config.hardware.facter.reportPath or null;
        description = "Path to a report generated by nixos-facter.";
      };

      report = mkOption {
        type = attrsOf anything;
        default =
          config.hardware.facter.report
            or (if cfg.facter.reportPath == null then { } else fromJson (readfile cfg.facter.reportPath));
        description = "An import for the reportPath.";
      };
    };
  };

  config = {
    virtualisation.libvirt.enable = true;

    virtualisation.libvirt.connections."qemu:///system".domains = mapAttrsToList (name: vm: {
      definition = nixvirtLib.domain.writeXML vm._nixVirtSpec;
    }) cfg.vms;
  };
}
